<script lang="ts">
  import { onMount } from 'svelte';
  import { db } from '$lib/db/database';
  import { scanReceipt } from '$lib/services/ocr';
  import { addTransaction } from '$lib/services/finance';
  import { toDateInput } from '$lib/utils/format';
  let file:File|null=null;let preview='';let progress=0;let scanning=false;let rawText='';let accounts:any[]=[];let categories:any[]=[];
  let form={amount:0,merchant:'',date:toDateInput(),accountId:'',categoryId:'',notes:''};
  onMount(async()=>{accounts=await db.accounts.toArray();categories=await db.categories.where('type').equals('expense').toArray();form.accountId=accounts[0]?.id||'';});
  function choose(e:Event){const f=(e.currentTarget as HTMLInputElement).files?.[0];if(!f)return;file=f;preview=URL.createObjectURL(f);rawText='';}
  async function run(){if(!file)return;scanning=true;progress=0;try{const r=await scanReceipt(file,p=>progress=p);rawText=r.rawText;form.amount=r.amount;form.merchant=r.merchant;}catch(e){alert('OCR gagal: '+(e as Error).message)}finally{scanning=false;}}
  async function save(){if(!form.amount||!form.accountId)return alert('Nominal dan akun wajib diisi.');await addTransaction({type:'expense',amount:Number(form.amount),date:new Date(form.date).toISOString(),accountId:form.accountId,categoryId:form.categoryId||undefined,merchant:form.merchant,notes:form.notes,receiptImage:file||undefined,source:'ocr'});alert('Transaksi hasil OCR berhasil disimpan.');location.href='/transaksi';}
</script>
<div class="page-title"><div><h1>Scan Struk OCR</h1><div class="muted">Pemrosesan dilakukan lokal di browser</div></div></div>
<div class="grid two-col"><div class="card"><h3>1. Pilih Foto Struk</h3><div class="ocr-box"><input type="file" accept="image/*" capture="environment" onchange={choose}/><p class="muted">Gunakan gambar terang, lurus, dan tidak blur.</p>{#if preview}<img class="receipt-preview" src={preview} alt="Preview struk"/>{/if}</div>{#if file}<button class="primary" style="margin-top:14px;width:100%" disabled={scanning} onclick={run}>{scanning?`Memproses ${progress}%`:'Mulai OCR'}</button>{/if}{#if scanning}<div class="bar" style="margin-top:12px"><span style={`width:${progress}%`}></span></div>{/if}{#if rawText}<details style="margin-top:14px"><summary>Teks mentah OCR</summary><pre style="white-space:pre-wrap;font-size:12px">{rawText}</pre></details>{/if}</div><div class="card"><h3>2. Koreksi & Simpan</h3><div class="form-grid"><div class="field"><label>Merchant</label><input bind:value={form.merchant}/></div><div class="field"><label>Nominal</label><input type="number" bind:value={form.amount}/></div><div class="field"><label>Tanggal</label><input type="datetime-local" bind:value={form.date}/></div><div class="field"><label>Akun</label><select bind:value={form.accountId}>{#each accounts as a}<option value={a.id}>{a.name}</option>{/each}</select></div><div class="field full"><label>Kategori</label><select bind:value={form.categoryId}><option value="">Pilih kategori</option>{#each categories as c}<option value={c.id}>{c.icon} {c.name}</option>{/each}</select></div><div class="field full"><label>Catatan</label><textarea rows="3" bind:value={form.notes}></textarea></div></div><button class="primary" style="margin-top:16px;width:100%" onclick={save}>Simpan Transaksi</button></div></div>
