<script lang="ts">
  import { onMount } from 'svelte';
  import { db } from '$lib/db/database';
  import type { Account, Category, Transaction, TransactionInput, TransactionType } from '$lib/db/types';
  import { addTransaction, deleteTransaction, updateTransaction } from '$lib/services/finance';
  import { rupiah, formatDate, toDateInput } from '$lib/utils/format';
  import { Pencil, Plus, Trash2, X } from 'lucide-svelte';
  let transactions: Transaction[] = [], accounts: Account[] = [], categories: Category[] = [];
  let showForm = false, editingId: string | null = null, query = '', typeFilter: TransactionType | 'all' = 'all', error = '', dirty = false;
  let form = emptyForm();
  function emptyForm(): TransactionInput { return { type: 'expense', amount: 0, date: toDateInput(), accountId: accounts?.[0]?.id || '', categoryId: '', merchant: '', notes: '', source: 'manual' }; }
  async function load() { [transactions, accounts, categories] = await Promise.all([db.transactions.orderBy('date').reverse().toArray(), db.accounts.toArray(), db.categories.toArray()]); if (!form.accountId && accounts[0]) form.accountId = accounts[0].id; }
  function openForm(tx?: Transaction) { error = ''; dirty = false; editingId = tx?.id || null; form = tx ? { type: tx.type, amount: tx.amount, date: toDateInput(new Date(tx.date)), accountId: tx.accountId, destinationAccountId: tx.destinationAccountId, categoryId: tx.categoryId, merchant: tx.merchant, paymentMethod: tx.paymentMethod, notes: tx.notes, tags: tx.tags, receiptImage: tx.receiptImage, source: tx.source } : emptyForm(); showForm = true; }
  function closeForm() { if (dirty && !confirm('Perubahan belum disimpan. Tutup form?')) return; showForm = false; }
  async function save() { error = ''; try { const payload: TransactionInput = { ...form, amount: Number(form.amount), date: new Date(form.date).toISOString(), categoryId: form.type === 'transfer' ? undefined : form.categoryId || undefined, destinationAccountId: form.type === 'transfer' ? form.destinationAccountId : undefined }; if (editingId) await updateTransaction(editingId, payload); else await addTransaction(payload); dirty = false; showForm = false; await load(); } catch (cause) { error = (cause as Error).message; } }
  async function remove(id: string) { if (confirm('Hapus transaksi ini?')) { await deleteTransaction(id); await load(); } }
  $: filtered = transactions.filter((tx) => (typeFilter === 'all' || tx.type === typeFilter) && `${tx.merchant || ''} ${tx.notes || ''}`.toLowerCase().includes(query.toLowerCase()));
  $: filteredCategories = categories.filter((category) => category.type === (form.type === 'income' ? 'income' : 'expense'));
  onMount(() => { load().then(() => { if (new URLSearchParams(location.search).has('new')) openForm(); }); });
</script>
<div class="page-title"><div><h1>Transaksi</h1><div class="muted">Input manual dan kelola seluruh riwayat</div></div><button class="primary" onclick={() => openForm()}><Plus size={18}/> Tambah</button></div>
<div class="card"><div class="filters"><input placeholder="Cari merchant / catatan..." bind:value={query}/><select bind:value={typeFilter}><option value="all">Semua jenis</option><option value="income">Pemasukan</option><option value="expense">Pengeluaran</option><option value="transfer">Transfer</option></select><a class="secondary" href="/scan">Scan OCR</a></div><div class="table-wrap"><table class="table responsive-table"><thead><tr><th>Tanggal</th><th>Jenis</th><th>Merchant</th><th>Kategori/Tujuan</th><th>Nominal</th><th>Aksi</th></tr></thead><tbody>
{#each filtered as tx}<tr><td data-label="Tanggal">{formatDate(tx.date)}</td><td data-label="Jenis"><span class="pill">{tx.type}</span></td><td data-label="Merchant">{tx.merchant || '-'}</td><td data-label="Kategori/Tujuan">{tx.type === 'transfer' ? `→ ${accounts.find((a) => a.id === tx.destinationAccountId)?.name || '-'}` : categories.find((c) => c.id === tx.categoryId)?.name || '-'}</td><td data-label="Nominal" class:danger={tx.type === 'expense'} class:good={tx.type === 'income'}>{rupiah(tx.amount)}</td><td data-label="Aksi"><div class="actions"><button class="secondary icon-btn" aria-label="Edit transaksi" onclick={() => openForm(tx)}><Pencil size={15}/></button><button class="danger-btn" aria-label="Hapus transaksi" onclick={() => remove(tx.id)}><Trash2 size={15}/></button></div></td></tr>{/each}
</tbody></table>{#if !filtered.length}<div class="empty">Tidak ada transaksi.</div>{/if}</div></div>
{#if showForm}<div class="modal" role="presentation" onclick={(event) => { if (event.currentTarget === event.target) closeForm(); }}><div class="card modal-card" role="dialog" aria-modal="true" aria-labelledby="transaction-title" oninput={() => dirty = true}><div class="page-title"><h2 id="transaction-title">{editingId ? 'Edit' : 'Tambah'} Transaksi</h2><button class="secondary icon-btn" aria-label="Tutup" onclick={closeForm}><X size={18}/></button></div>{#if error}<div class="notice danger-notice">{error}</div>{/if}<div class="form-grid">
<div class="field"><label for="type">Jenis</label><select id="type" bind:value={form.type}><option value="expense">Pengeluaran</option><option value="income">Pemasukan</option><option value="transfer">Transfer</option></select></div><div class="field"><label for="amount">Nominal</label><input id="amount" type="number" min="1" required bind:value={form.amount}/></div><div class="field"><label for="date">Tanggal</label><input id="date" type="datetime-local" required bind:value={form.date}/></div><div class="field"><label for="account">Akun {form.type === 'transfer' ? 'asal' : ''}</label><select id="account" required bind:value={form.accountId}>{#each accounts as account}<option value={account.id}>{account.name}</option>{/each}</select></div>
{#if form.type === 'transfer'}<div class="field full"><label for="destination">Akun tujuan</label><select id="destination" required bind:value={form.destinationAccountId}><option value="">Pilih akun tujuan</option>{#each accounts.filter((account) => account.id !== form.accountId) as account}<option value={account.id}>{account.name}</option>{/each}</select></div>{:else}<div class="field"><label for="category">Kategori</label><select id="category" required bind:value={form.categoryId}><option value="">Pilih kategori</option>{#each filteredCategories as category}<option value={category.id}>{category.icon} {category.name}</option>{/each}</select></div><div class="field"><label for="merchant">Merchant</label><input id="merchant" bind:value={form.merchant}/></div>{/if}
<div class="field full"><label for="notes">Catatan</label><textarea id="notes" rows="3" bind:value={form.notes}></textarea></div></div><div class="actions form-actions"><button class="primary" onclick={save}>Simpan Transaksi</button><button class="secondary" onclick={closeForm}>Batal</button></div></div></div>{/if}
