<script lang="ts">
  import { onMount } from 'svelte';
  import { db } from '$lib/db/database';
  import { addTransaction, deleteTransaction } from '$lib/services/finance';
  import { rupiah, formatDate, toDateInput } from '$lib/utils/format';
  import { Plus, Trash2, X } from 'lucide-svelte';
  let transactions:any[]=[]; let accounts:any[]=[]; let categories:any[]=[]; let showForm=false; let query=''; let typeFilter='all';
  let form = { type:'expense', amount:0, date:toDateInput(), accountId:'', categoryId:'', merchant:'', notes:'', source:'manual' as const };

  async function load(){transactions=await db.transactions.orderBy('date').reverse().toArray();accounts=await db.accounts.toArray();categories=await db.categories.toArray();if(!form.accountId&&accounts[0])form.accountId=accounts[0].id;}
  function openForm(){form={type:'expense',amount:0,date:toDateInput(),accountId:accounts[0]?.id||'',categoryId:'',merchant:'',notes:'',source:'manual'};showForm=true;}
  async function save(){if(!form.amount||!form.accountId)return alert('Nominal dan akun wajib diisi.');await addTransaction({...form, type:form.type as any, date:new Date(form.date).toISOString(), categoryId:form.categoryId||undefined});showForm=false;await load();}
  async function remove(id:string){if(confirm('Hapus transaksi ini?')){await deleteTransaction(id);await load();}}
  $: filtered=transactions.filter(t=>(typeFilter==='all'||t.type===typeFilter)&&`${t.merchant||''} ${t.notes||''}`.toLowerCase().includes(query.toLowerCase()));
  onMount(()=>{load(); if(new URLSearchParams(location.search).has('new')) setTimeout(openForm,100);});
</script>
<div class="page-title"><div><h1>Transaksi</h1><div class="muted">Input manual dan kelola seluruh riwayat</div></div><button class="primary" onclick={openForm}><Plus size={18}/> Tambah</button></div>
<div class="card"><div class="filters"><input placeholder="Cari merchant / catatan..." bind:value={query}/><select bind:value={typeFilter}><option value="all">Semua jenis</option><option value="income">Pemasukan</option><option value="expense">Pengeluaran</option><option value="transfer">Transfer</option></select><a class="secondary" href="/scan">Scan OCR</a></div><div class="table-wrap"><table class="table"><thead><tr><th>Tanggal</th><th>Jenis</th><th>Merchant</th><th>Kategori</th><th>Nominal</th><th></th></tr></thead><tbody>{#each filtered as tx}<tr><td>{formatDate(tx.date)}</td><td><span class="pill">{tx.type}</span></td><td>{tx.merchant||'-'}</td><td>{categories.find(c=>c.id===tx.categoryId)?.name||'-'}</td><td class:danger={tx.type==='expense'} class:good={tx.type==='income'}>{rupiah(tx.amount)}</td><td><button class="danger-btn" onclick={()=>remove(tx.id)}><Trash2 size={15}/></button></td></tr>{/each}</tbody></table>{#if !filtered.length}<div class="empty">Tidak ada transaksi.</div>{/if}</div></div>
{#if showForm}<div style="position:fixed;inset:0;background:rgba(0,0,0,.45);z-index:20;display:grid;place-items:center;padding:16px" onclick={(e)=>{if(e.currentTarget===e.target)showForm=false}}><div class="card" style="width:min(620px,100%);max-height:90vh;overflow:auto"><div class="page-title"><h2>Tambah Transaksi</h2><button class="secondary" onclick={()=>showForm=false}><X size={18}/></button></div><div class="form-grid"><div class="field"><label>Jenis</label><select bind:value={form.type}><option value="expense">Pengeluaran</option><option value="income">Pemasukan</option><option value="transfer">Transfer</option></select></div><div class="field"><label>Nominal</label><input type="number" min="0" bind:value={form.amount}/></div><div class="field"><label>Tanggal</label><input type="datetime-local" bind:value={form.date}/></div><div class="field"><label>Akun</label><select bind:value={form.accountId}>{#each accounts as a}<option value={a.id}>{a.name}</option>{/each}</select></div><div class="field"><label>Kategori</label><select bind:value={form.categoryId}><option value="">Tanpa kategori</option>{#each categories.filter(c=>c.type===(form.type==='income'?'income':'expense')) as c}<option value={c.id}>{c.icon} {c.name}</option>{/each}</select></div><div class="field"><label>Merchant</label><input bind:value={form.merchant}/></div><div class="field full"><label>Catatan</label><textarea rows="3" bind:value={form.notes}></textarea></div></div><div class="actions" style="margin-top:16px"><button class="primary" onclick={save}>Simpan Transaksi</button><button class="secondary" onclick={()=>showForm=false}>Batal</button></div></div></div>{/if}
