<script lang="ts">
  import { onMount } from 'svelte';
  import { liveQuery } from 'dexie';
  import { db } from '$lib/db/database';
  import type { Account, Budget, Category, RecurringRule, Transaction } from '$lib/db/types';
  import { calculateAccountBalances } from '$lib/services/finance';
  import { setTheme } from '$lib/stores/theme';
  import { exportJSON, inspectBackup, restoreBackup } from '$lib/services/export';
  import { rupiah } from '$lib/utils/format';
  import { addRecurringRule, generateDueTransactions, skipRecurringOccurrence, updateRecurringRule } from '$lib/services/recurring';
  let accounts: Account[] = [], categories: Category[] = [], budgets: Budget[] = [], transactions: Transaction[] = [];
  let newAccount = '', newCategory = '', budgetCategory = '', budgetLimit = 0, restoreMode: 'replace' | 'merge' = 'replace';
  let recurringRules: RecurringRule[] = [], recurringType: 'income' | 'expense' = 'expense', recurringAmount = 0, recurringAccount = '', recurringCategory = '', recurringMerchant = '', recurringDate = new Date().toLocaleDateString('sv-SE'), recurringError = '', editingRecurringId: string | null = null;
  const month = new Date().toISOString().slice(0, 7);
  async function load() { [accounts, categories, budgets, transactions, recurringRules] = await Promise.all([db.accounts.toArray(), db.categories.toArray(), db.budgets.where('month').equals(month).toArray(), db.transactions.toArray(), db.recurringRules.toArray()]); if (!budgetCategory) budgetCategory = categories.find((category) => category.type === 'expense')?.id || ''; if (!recurringAccount) recurringAccount = accounts[0]?.id || ''; }
  async function saveRecurring() { recurringError = ''; try { const input = { type: recurringType, amount: Number(recurringAmount), accountId: recurringAccount, categoryId: recurringCategory, merchant: recurringMerchant, nextDate: recurringDate }; if (editingRecurringId) await updateRecurringRule(editingRecurringId, input); else await addRecurringRule(input); await generateDueTransactions(); editingRecurringId = null; recurringAmount = 0; recurringMerchant = ''; await load(); } catch (error) { recurringError = (error as Error).message; } }
  function editRecurring(rule: RecurringRule) { editingRecurringId = rule.id; recurringType = rule.type; recurringAmount = rule.amount; recurringAccount = rule.accountId; recurringCategory = rule.categoryId; recurringMerchant = rule.merchant || ''; recurringDate = rule.nextDate; recurringError = ''; }
  async function toggleRecurring(rule: RecurringRule) { await db.recurringRules.update(rule.id, { paused: !rule.paused }); if (rule.paused) await generateDueTransactions(); await load(); }
  async function skipRecurring(rule: RecurringRule) { if (!confirm(`Lewati transaksi tanggal ${rule.nextDate}?`)) return; await skipRecurringOccurrence(rule.id); await load(); }
  async function removeRecurring(id: string) { if (!confirm('Hapus aturan berulang ini? Transaksi yang sudah dibuat tetap tersimpan.')) return; await db.recurringRules.delete(id); await load(); }
  async function addAccount() { if (!newAccount.trim()) return; await db.accounts.add({ id: crypto.randomUUID(), name: newAccount.trim(), type: 'other', initialBalance: 0, createdAt: new Date().toISOString() }); newAccount = ''; await load(); }
  async function addCategory() { if (!newCategory.trim()) return; await db.categories.add({ id: crypto.randomUUID(), name: newCategory.trim(), type: 'expense', icon: '📌' }); newCategory = ''; await load(); }
  async function saveBudget() { if (!budgetCategory || budgetLimit <= 0) return; const existing = budgets.find((budget) => budget.categoryId === budgetCategory); await db.budgets.put({ id: existing?.id || crypto.randomUUID(), categoryId: budgetCategory, month, limit: Number(budgetLimit) }); budgetLimit = 0; await load(); }
  async function restore(event: Event) { const input = event.currentTarget as HTMLInputElement; const file = input.files?.[0]; if (!file) return; try { const backup = await inspectBackup(file); const summary = `${backup.transactions.length} transaksi, ${backup.accounts.length} akun, ${backup.categories.length} kategori`; if (!confirm(`Backup berisi ${summary}. ${restoreMode === 'replace' ? 'Data saat ini akan diganti.' : 'Data yang ID-nya sama akan dipertahankan; data baru ditambahkan.'} Lanjutkan?`)) return; await exportJSON('snapshot-sebelum-restore'); const result = await restoreBackup(file, restoreMode); const skipped = Object.entries(result.skipped).filter(([, count]) => count > 0).map(([name, count]) => `${count} ${name}`).join(', '); alert(`Restore berhasil. Snapshot data sebelumnya telah diunduh.${skipped ? ` Data lokal dipertahankan untuk: ${skipped}.` : ''}`); location.reload(); } catch (error) { alert((error as Error).message); } finally { input.value = ''; } }
  async function wipe() { if (confirm('PERINGATAN: Semua data lokal akan dihapus. Lanjutkan?')) { await db.delete(); location.reload(); } }
  async function enableNotifications() { if (!('Notification' in window)) return alert('Browser ini tidak mendukung notifikasi.'); const permission = await Notification.requestPermission(); alert(permission === 'granted' ? 'Notifikasi anggaran aktif.' : 'Izin notifikasi tidak diberikan.'); }
  $: balances = calculateAccountBalances(accounts, transactions);
  $: expenseCategories = categories.filter((category) => category.type === 'expense');
  $: recurringCategories = categories.filter((category) => category.type === recurringType);
  $: if (recurringCategories.length && !recurringCategories.some((category) => category.id === recurringCategory)) recurringCategory = recurringCategories[0].id;
  $: budgetRows = budgets.map((budget) => { const spent = transactions.filter((tx) => tx.type === 'expense' && tx.categoryId === budget.categoryId && tx.date.slice(0, 7) === month).reduce((sum, tx) => sum + tx.amount, 0); return { ...budget, name: categories.find((category) => category.id === budget.categoryId)?.name || '-', spent, pct: Math.min(100, spent / budget.limit * 100) }; });
  onMount(() => { const subscription = liveQuery(() => Promise.all([db.accounts.toArray(), db.categories.toArray(), db.budgets.where('month').equals(month).toArray(), db.transactions.toArray(), db.recurringRules.toArray()])).subscribe(([newAccounts, newCategories, newBudgets, newTransactions, newRules]) => { accounts = newAccounts; categories = newCategories; budgets = newBudgets; transactions = newTransactions; recurringRules = newRules; if (!budgetCategory) budgetCategory = categories.find((category) => category.type === 'expense')?.id || ''; if (!recurringAccount) recurringAccount = accounts[0]?.id || ''; }); if (navigator.storage?.persist) navigator.storage.persist(); return () => subscription.unsubscribe(); });
</script>
<div class="page-title"><div><h1>Pengaturan</h1><div class="muted">Akun, anggaran, tampilan, dan perlindungan data</div></div></div>
<div class="grid two-col"><div class="grid"><div class="card"><h3>Tampilan</h3><div class="actions"><button class="secondary" onclick={() => setTheme('light')}>☀ Light</button><button class="secondary" onclick={() => setTheme('dark')}>🌙 Dark</button><button class="secondary" onclick={() => setTheme('system')}>◐ System</button></div></div>
<div class="card"><h3>Akun / Dompet</h3><div class="actions"><input aria-label="Nama akun baru" placeholder="Nama akun baru" bind:value={newAccount}/><button class="primary" onclick={addAccount}>Tambah</button></div><ul class="summary-list">{#each accounts as account}<li><span>{account.name} <small class="muted">({account.type})</small></span><strong>{rupiah(balances.get(account.id) || 0)}</strong></li>{/each}</ul></div>
<div class="card"><h3>Kategori Pengeluaran</h3><div class="actions"><input aria-label="Kategori baru" placeholder="Kategori baru" bind:value={newCategory}/><button class="primary" onclick={addCategory}>Tambah</button></div><ul>{#each expenseCategories as category}<li>{category.icon} {category.name}</li>{/each}</ul></div></div>
<div class="grid"><div class="card"><h3>Anggaran Bulan Ini</h3><div class="form-grid"><div class="field"><label for="budget-category">Kategori</label><select id="budget-category" bind:value={budgetCategory}>{#each expenseCategories as category}<option value={category.id}>{category.icon} {category.name}</option>{/each}</select></div><div class="field"><label for="budget-limit">Batas</label><input id="budget-limit" type="number" min="1" bind:value={budgetLimit}/></div></div><button class="primary form-actions" onclick={saveBudget}>Simpan Anggaran</button>{#each budgetRows as budget}<div class="chart-row"><div><span>{budget.name}</span><strong class:danger={budget.spent >= budget.limit}>{rupiah(budget.spent)} / {rupiah(budget.limit)}</strong></div><div class="bar"><span class:bar-warning={budget.pct >= 80} class:bar-danger={budget.pct >= 100} style={`width:${budget.pct}%`}></span></div></div>{/each}</div>
<div class="card"><h3>Backup & Restore</h3><p class="muted">Restore divalidasi dan snapshot data saat ini diunduh otomatis.</p><div class="field"><label for="restore-mode">Mode restore</label><select id="restore-mode" bind:value={restoreMode}><option value="replace">Ganti seluruh data</option><option value="merge">Gabungkan berdasarkan ID</option></select></div><div class="actions form-actions"><button class="primary" onclick={() => exportJSON()}>Download Backup</button><label class="secondary file-button">Restore Backup<input hidden type="file" accept="application/json" onchange={restore}/></label></div></div>
<div class="card"><h3>Transaksi Berulang Bulanan</h3><p class="muted">Transaksi dibuat saat aplikasi dibuka pada atau setelah tanggal jadwal.</p>{#if recurringError}<div class="notice danger-notice">{recurringError}</div>{/if}<div class="form-grid"><div class="field"><label for="recurring-type">Jenis</label><select id="recurring-type" bind:value={recurringType}><option value="expense">Pengeluaran</option><option value="income">Pemasukan</option></select></div><div class="field"><label for="recurring-amount">Nominal</label><input id="recurring-amount" type="number" min="1" bind:value={recurringAmount}/></div><div class="field"><label for="recurring-account">Akun</label><select id="recurring-account" bind:value={recurringAccount}>{#each accounts as account}<option value={account.id}>{account.name}</option>{/each}</select></div><div class="field"><label for="recurring-category">Kategori</label><select id="recurring-category" bind:value={recurringCategory}>{#each recurringCategories as category}<option value={category.id}>{category.name}</option>{/each}</select></div><div class="field"><label for="recurring-merchant">Nama</label><input id="recurring-merchant" bind:value={recurringMerchant}/></div><div class="field"><label for="recurring-date">Mulai / berikutnya</label><input id="recurring-date" type="date" bind:value={recurringDate}/></div></div><div class="actions form-actions"><button class="primary" onclick={saveRecurring}>{editingRecurringId ? 'Perbarui Aturan' : 'Simpan Aturan'}</button>{#if editingRecurringId}<button class="secondary" onclick={() => { editingRecurringId = null; recurringAmount = 0; recurringMerchant = ''; }}>Batal Edit</button>{/if}</div><ul class="summary-list">{#each recurringRules as rule}<li><span>{rule.merchant || categories.find((category) => category.id === rule.categoryId)?.name || rule.type}<small class="muted"> · berikutnya {rule.nextDate}{rule.paused ? ' · dijeda' : ''}</small></span><span><strong>{rupiah(rule.amount)}</strong> <button class="secondary" onclick={() => editRecurring(rule)}>Edit</button> <button class="secondary" onclick={() => toggleRecurring(rule)}>{rule.paused ? 'Lanjutkan' : 'Jeda'}</button> <button class="secondary" onclick={() => skipRecurring(rule)}>Lewati</button> <button class="danger-btn" aria-label="Hapus aturan berulang" onclick={() => removeRecurring(rule.id)}>Hapus</button></span></li>{/each}</ul></div>
<div class="card"><h3>Data Lokal</h3><p class="muted">Aplikasi meminta persistent storage bila didukung browser. Backup berkala tetap disarankan.</p><div class="actions"><button class="secondary" onclick={enableNotifications}>Aktifkan Notifikasi Anggaran</button><button class="danger-btn" onclick={wipe}>Hapus Semua Data</button></div></div></div></div>
